version: '3.6'
networks:
  backend:
    name: diss-net-all
services:
  diss-backend:
    restart: always
    container_name: diss-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.cn-qingdao.aliyuncs.com/diss/diss-backend
    ports:
      - "10443:10443"
      - "10444:10444"
    depends_on:
      - diss-db
      - timescale-db
      - diss-nats-streaming
    volumes:
      - /var/lib/diss/diss-backend/upload/kubernetes:/opt/diss-backend/upload/kubernetes
      - /var/lib/diss/diss-backend/upload/vuln:/opt/diss-backend/upload/vuln
      - /var/lib/diss/diss-backend/upload/probe:/opt/diss-backend/upload/probe
      - /var/lib/diss/diss-backend/upload/virus:/opt/diss-backend/upload/virus
      - /var/lib/diss/diss-backend/upload/agent:/opt/diss-backend/upload/agent
      - /var/lib/diss/diss-backend/public:/opt/diss-backend/public
      - /var/log/diss/diss-backend:/opt/diss-backend/logs
      - ./conf:/opt/diss-backend/conf
    entrypoint:
      - ./entrypoint.sh
    networks:
      - backend
#    deploy:
#      resources:
#        limits:
#          cpus: '0.1'
#          memory: 1G

  diss-db:
    restart: unless-stopped
    container_name: diss-db
    image: registry.cn-qingdao.aliyuncs.com/diss/postgres:9-alpine3.14
    env_file:
      - conf/diss-db.env
    expose:
      - 5432
    volumes:
      - /var/lib/diss/db/diss-db:/var/lib/postgresql/data
    networks:
      - backend
#    deploy:
#      resources:
#        limits:
#          cpus: '0.1'
#          memory: 1G

  timescale-db:
    restart: always
    container_name: timescale-db
    image: registry.cn-qingdao.aliyuncs.com/diss/timescaledb:2.3.1-pg13
    volumes:
      - /var/lib/diss/db/timescale/:/var/lib/postgresql/data
    env_file:
      - conf/diss-db.env
    expose:
      - 5432
    networks:
      - backend
#    deploy:
#      resources:
#        limits:
#          cpus: '0.1'
#          memory: 1G

  diss-nats-streaming:
    restart: unless-stopped
    container_name: diss-nats-streaming
    image: registry.cn-qingdao.aliyuncs.com/diss/nats-streaming:latest
    ports:
      - 4222:4222
    command: -cid=diss-cluster -p 4222 -m 8222 --user "diss" --pass "dissP@ssw0rd"
    networks:
      - backend

