version: '3'
services:
  diss-backend:
    restart: always
    container_name: diss-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: diss-backend
    ports:
      - "8080:8080"
      - "10443:10443"
      - "8889:8889"
    env_file:
      - conf/diss-backend.env
      - deploy/diss-backend-db.env
    links:
      - diss-db
    depends_on:
      - diss-db
    volumes:
      - log:/opt/diss-backend/logs
      # to dev
#      - ./conf:/opt/diss-backend/conf
#      - ./swagger:/opt/diss-backend/swagger
#      - ./bin/diss-backend:/opt/diss-backend/diss-backend
#      - ./entrypoint.sh:/opt/diss-backend/entrypoint.sh
    entrypoint:
      - ./entrypoint.sh

  diss-db:
    restart: unless-stopped
    container_name: diss-db
    image: mysql:5.7.14
    env_file:
      - ./deploy/diss-backend-db.env
    command: [ #使用 command 可以覆盖容器启动后默认执行的命令
      '--character-set-server=utf8', #设置数据库表的数据集
      '--collation-server=utf8_general_ci' #设置数据库表的数据集
    ]
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - ./conf/my.cnf:/etc/my.cnf
#      - /tmp/diss/mysql/log:/var/log/mysql
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro
#
volumes:
  log:
  mysql: