apiVersion: v1
kind: Service
metadata:
  name: diss-backend
  labels:
    app: diss-backend
spec:
  selector:
    app: diss-backend
  ports:
  - name: dev
    port: 8080
    nodePort:30006
    targetPort: dev
  - name: prod
    port: 8088
    targetPort: prod
  - name: https
    port: 443
    targetPort: https