apiVersion: v1
kind: Service
metadata:
  name: diss-db
  labels:
    app: diss-db
spec:
  ports:
  - port: 3306
  selector:
    app: diss-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: diss-db
  name: diss-db
spec:
  serviceName: diss-db
  replicas: 1
  selector:
    matchLabels:
      app: diss-db
  template:
    metadata:
      labels:
        app: diss-db
    spec:
      containers:
      - image: mysql:5.7.14
        name: diss-db
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
          hostPort: 3306
        volumeMounts:
        - name: diss-data
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: diss-env
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              key: MYSQL_USER
              name: diss-env
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_PASSWORD
              name: diss-env
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: diss-env
      volumes:
      - name: diss-data
        emptyDir: {}