apiVersion: v1
data:
  DS_Diss_Api_Pwd: mysecretpassword
  DS_Security_Log_Pwd: password
  Nats_Pwd: diss
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: diss-backend-conf-diss-backend-env-secret
  name: conf-diss-backend-env-secret
  namespace: diss
