apiVersion: v1
data:
  POSTGRES_PASSWORD: diss
  POSTGRES_ROOT_PASSWORD: diss
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: diss-backend-conf-diss-backend-db-postgres-env-secret
  name: conf-diss-backend-db-postgres-env-secret
  namespace: diss
