apiVersion: v1
data:
  Address: http://114.67.110.120:9200,
  DEFAULT_HOST: diss-db
  DEFAULT_PORT: "5432"
  DS_Diss_Api_DB_Name: postgres
  DS_Diss_Api_Host: 114.67.110.120
  DS_Diss_Api_Port: "2345"
  DS_Diss_Api_User: postgres
  DS_Security_Log_DB_Name: postgres
  DS_Security_Log_Host: 114.67.110.120
  DS_Security_Log_Port: "5432"
  DS_Security_Log_User: postgres
  Nats_Client_Id: diss-server
  Nats_Cluster_Id: diss-cluster
  Nats_Enable: "true"
  Nats_Ip: diss-nats-streaming
  Nats_Port: "4222"
  Nats_Prefix: nats://
  Nats_User: diss
  RunMode: prod
  UserName: elastic
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: diss-backend-conf-diss-backend-env
  name: conf-diss-backend-env
  namespace: diss
