apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-prod.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: diss-backend
  name: diss-backend
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
    nodePort: 30080
  - name: "https"
    port: 10443
    targetPort: 10443
  type: NodePort
  selector:
    io.kompose.service: diss-backend
status:
  loadBalancer: {}
