apiVersion: v1
data:
  POSTGRES_PASSWORD: ZGlzc1BAc3N3MHJkCg==
  POSTGRES_ROOT_PASSWORD: ZGlzc1BAc3N3MHJkCg==
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    origin: diss
    app: diss-db
  name: diss-db-env-secret
  namespace: diss
