apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-prod.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: diss-db
  name: diss-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: diss-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-prod.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: diss-db
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: conf-diss-backend-db-postgres-env
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: conf-diss-backend-db-postgres-env
        - name: POSTGRES_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_ROOT_PASSWORD
              name: conf-diss-backend-db-postgres-env
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: conf-diss-backend-db-postgres-env
        image: postgres:9.6
        imagePullPolicy: ""
        name: diss-db
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: diss-db-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: diss-db-claim0
        hostPath:
          path: /tmp/diss/postgres
          type: DirectoryOrCreate
status: {}
