apiVersion: v1
kind: Service
metadata:
  labels:
    origin: diss
    app: diss-backend
  name: diss-backend
  namespace: diss
spec:
  ports:
  - name: "10443"
    port: 10443
    targetPort: 10443
#    nodePort: 30444
#  type: LoadBalancer
  type: ClusterIP
  selector:
    origin: diss
    app: diss-backend
status:
  loadBalancer: {}
