apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose-prod.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: diss-db
  name: diss-db
  namespace: diss
spec:
  ports:
  - name: "5432"
    port: 5432
  selector:
    io.kompose.service: diss-db
status:
  loadBalancer: {}
