apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose-prod.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: diss-db
  name: diss-db
  namespace: diss
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: diss-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../docker-compose-prod.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: diss-db
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: conf-diss-backend-db-postgres-env
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: conf-diss-backend-db-postgres-env-secret
        - name: POSTGRES_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_ROOT_PASSWORD
              name: conf-diss-backend-db-postgres-env-secret
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: conf-diss-backend-db-postgres-env
        image: postgres:9.6
        imagePullPolicy: IfNotPresent
        name: diss-db
        ports:
        - containerPort: 5432
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /var/lib/diss/postgres
            name: diss-db-data
            subPath: data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: diss-db-data
        emptyDir: {}
status: {}
