apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose-prod.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: diss-backend
  name: diss-backend
  namespace: diss
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: diss-backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../docker-compose-prod.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: diss-backend
    spec:
      containers:
      - command:
        - ./entrypoint.sh
        env:
        - name: Address
          valueFrom:
            configMapKeyRef:
              key: Address
              name: conf-diss-backend-env
        - name: DEFAULT_HOST
          valueFrom:
            configMapKeyRef:
              key: DEFAULT_HOST
              name: conf-diss-backend-env
        - name: DEFAULT_PORT
          valueFrom:
            configMapKeyRef:
              key: DEFAULT_PORT
              name: conf-diss-backend-env
        - name: DS_Diss_Api_DB_Name
          valueFrom:
            configMapKeyRef:
              key: DS_Diss_Api_DB_Name
              name: conf-diss-backend-env
        - name: DS_Diss_Api_Host
          valueFrom:
            configMapKeyRef:
              key: DS_Diss_Api_Host
              name: conf-diss-backend-env
        - name: DS_Diss_Api_Port
          valueFrom:
            configMapKeyRef:
              key: DS_Diss_Api_Port
              name: conf-diss-backend-env
        - name: DS_Diss_Api_Pwd
          valueFrom:
            secretKeyRef:
              key: DS_Diss_Api_Pwd
              name: conf-diss-backend-env-secret
        - name: DS_Diss_Api_User
          valueFrom:
            configMapKeyRef:
              key: DS_Diss_Api_User
              name: conf-diss-backend-env
        - name: DS_Security_Log_DB_Name
          valueFrom:
            configMapKeyRef:
              key: DS_Security_Log_DB_Name
              name: conf-diss-backend-env
        - name: DS_Security_Log_Host
          valueFrom:
            configMapKeyRef:
              key: DS_Security_Log_Host
              name: conf-diss-backend-env
        - name: DS_Security_Log_Port
          valueFrom:
            configMapKeyRef:
              key: DS_Security_Log_Port
              name: conf-diss-backend-env
        - name: DS_Security_Log_Pwd
          valueFrom:
            secretKeyRef:
              key: DS_Security_Log_Pwd
              name: conf-diss-backend-env-secret
        - name: DS_Security_Log_User
          valueFrom:
            configMapKeyRef:
              key: DS_Security_Log_User
              name: conf-diss-backend-env
        - name: Nats_Client_Id
          valueFrom:
            configMapKeyRef:
              key: Nats_Client_Id
              name: conf-diss-backend-env
        - name: Nats_Cluster_Id
          valueFrom:
            configMapKeyRef:
              key: Nats_Cluster_Id
              name: conf-diss-backend-env
        - name: Nats_Enable
          valueFrom:
            configMapKeyRef:
              key: Nats_Enable
              name: conf-diss-backend-env
        - name: Nats_Ip
          valueFrom:
            configMapKeyRef:
              key: Nats_Ip
              name: conf-diss-backend-env
        - name: Nats_Port
          valueFrom:
            configMapKeyRef:
              key: Nats_Port
              name: conf-diss-backend-env
        - name: Nats_Prefix
          valueFrom:
            configMapKeyRef:
              key: Nats_Prefix
              name: conf-diss-backend-env
        - name: Nats_Pwd
          valueFrom:
            secretKeyRef:
              key: Nats_Pwd
              name: conf-diss-backend-env-secret
        - name: Nats_User
          valueFrom:
            configMapKeyRef:
              key: Nats_User
              name: conf-diss-backend-env
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: conf-diss-backend-db-postgres-env
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: conf-diss-backend-db-postgres-env-secret
        - name: POSTGRES_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_ROOT_PASSWORD
              name: conf-diss-backend-db-postgres-env-secret
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: conf-diss-backend-db-postgres-env
        - name: RunMode
          valueFrom:
            configMapKeyRef:
              key: RunMode
              name: conf-diss-backend-env
        - name: UserName
          valueFrom:
            configMapKeyRef:
              key: UserName
              name: conf-diss-backend-env
        image: registry.cn-qingdao.aliyuncs.com/diss/diss-backend:latest
        imagePullPolicy: IfNotPresent
        name: diss-backend
        ports:
        - containerPort: 8080
        - containerPort: 10443
        - containerPort: 8889
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /swagger
            port: 10443
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      serviceAccountName: ""
status: {}
