apiVersion: v1
kind: Service
metadata:
  labels:
    origin: diss
    app: diss-db
  name: diss-db
  namespace: diss
spec:
  ports:
  - name: "5432"
    port: 5432
  selector:
    origin: diss
    app: diss-db